import {
  Activity,
  ArrowDownUp,
  Bookmark,
  ChevronRight,
  Clock,
  Flag,
  Gauge,
  Map,
  Maximize2,
  Minus,
  Pause,
  Play,
  Plus,
  Radio,
  RotateCcw,
  Search,
  Settings2,
  SlidersHorizontal,
  Star,
  WifiOff,
  X,
  Download,
  Upload,
  Sun,
  Check,
  TriangleAlert,
  type LucideProps,
} from 'lucide-react';
const icons = {
  activity: Activity,
  sort: ArrowDownUp,
  bookmark: Bookmark,
  chevron: ChevronRight,
  clock: Clock,
  flag: Flag,
  gauge: Gauge,
  map: Map,
  fit: Maximize2,
  minus: Minus,
  pause: Pause,
  play: Play,
  plus: Plus,
  reset: RotateCcw,
  radio: Radio,
  search: Search,
  settings: Settings2,
  controls: SlidersHorizontal,
  star: Star,
  offline: WifiOff,
  close: X,
  download: Download,
  upload: Upload,
  sun: Sun,
  check: Check,
  alert: TriangleAlert,
};
export function Icon({ name, ...props }: LucideProps & { name: keyof typeof icons }) {
  const Component = icons[name];
  return <Component size={18} strokeWidth={1.7} aria-hidden="true" {...props} />;
}
